import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        {/* Simple top nav with auth links for discoverability */}
        <div className="sticky top-0 z-40 backdrop-blur supports-[backdrop-filter]:bg-background/70 border-b">
          <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
            <Link href="/" className="font-semibold tracking-tight">Gym Admin</Link>
            <div className="flex items-center gap-3">
              <Link href="/login" className="rounded-md px-3 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground">Login</Link>
              <Link href="/register" className="rounded-md bg-primary text-primary-foreground px-3 py-1.5 text-sm hover:opacity-90">Create account</Link>
            </div>
          </div>
        </div>
        {children}
        <Toaster richColors position="top-right" />
        <VisualEditsMessenger />
      </body>
    </html>
  );
}